### ISSUE TITLE
getAccountHistory отдаёт кол-во элементов на 1 больше чем limit по описанию

### ISSUE THREAD

**Issue by serdrdoor** [golos-blockchain/libs#12]
В методе getAccountHistory обнаружил не задокументированное поведение, ранее, как предшествующих версиях golos-js, так и в родственных предках графеноподобных библиотек лимит означал лимит, а теперь отдаётся значение на 1 большее.

Вот тут текущее описание:
https://wiki.golos.id/developers/api/cli-wallet#get_account_history

Вероятно проблема присутствует и в других аналогичных методах при запросе кол-в, где имеется limit.
На каком уровне проблема, либо на уровне библиотеки JS или же на стороне ноды блокчейна, не знаю.

**Comment by 1aerostorm** [comment]
> Вероятно проблема присутствует и в других аналогичных методах при запросе кол-в, где имеется limit.

Нет, в других методах такой проблемы не наблюдается. (Если вам известно, сообщите.)
Она не связана с golos-lib-js и ее версиями, а связана с нодами блокчейна, и она была всегда. Сейчас исправляем.

**Comment by Lex-Ai** [comment]
> В методе getAccountHistory обнаружил не задокументированное поведение, ранее, как предшествующих версиях golos-js, так и в родственных предках графеноподобных библиотек лимит означал лимит, а теперь отдаётся значение на 1 большее.
> 
> Вот тут текущее описание: https://wiki.golos.id/developers/api/cli-wallet#get_account_history
> 
> Вероятно проблема присутствует и в других аналогичных методах при запросе кол-в, где имеется limit. На каком уровне проблема, либо на уровне библиотеки JS или же на стороне ноды блокчейна, не знаю.

фикс в 0.26.2 бранче
https://github.com/golos-blockchain/chain-node/pull/194/commits/faab0d2e0db377d7ab8781c58dbf195ba7553c67
